### PR TITLE
Added three things

### PR DESCRIPTION
**Pull request by stcrowe**
Why didn't you upload .hpp files to the github? Without the .hpp files, how can anyone fork and improve the mod? I added all the missing files back in. 

My specific changes (which are hard to find due to all the missing files):

- Added ACE heal module to instantly heal a unit or player

- Fixed the compositions so they work in the Eden Editor - may mess with the advance composition thingy... I didn't check it out.

Great mod, hope you like my changes.

(Side note, the mod has a bunch of .hpp files setup in folders, but everything is done in the config. I guess your planning in the future to compartmentalize the mod. I would do it soon, because it took me about 20 minutes to realize that all those .hpp files in their subfolders are not even being #included, and that everything was in the config.)

### CODE REVIEW

**Comment by oOKexOo** [comment]
Hey stcrowe. 
Thanks for your effort. I will have a look on it.
I'm still learning when it comes to github and it seems I forgot to pull the final changes from 0.0.2 to master. Furthermore, for whatever reason the config folder is missing in the master branch, whereas it is present in all other branches. I definitely have to clean up stuff here.

**Comment by stcrowe** [comment]
I have uploaded all the missing files on my fork. So if you want you can merge my fork into the main branch,  Or, you can fix your main branch, and I'll refork it, add my changes, and make another pull request.

Don't feel like you have to accept my changed, but I've been wanting to make changes to the Ares mod for a while now. So, I might be contributing a lot to your project.

It's hard to see what changes I've made, but I think you'll like them. The files I changed specifically where:

Archilles/cfgFunctionsACE.hpp
Archilles/cfgVehiclesACE.hpp
/config.cpp
/Compositions/compositions.hpp


FYI, your .gitignore is set to ignore all files that end with *.hpp, plus some other random files.

**Comment by oOKexOo** [comment]
I completely changed the add-on structure. Hence, the merge won't work. Don't worry. I will add your changes to the new branch by hand. Hence, it will be part of the next update.

**Comment by oOKexOo** [comment]
Changes were integrated in branch 0.0.3

**Pull request closed without merging**
