### PR TITLE
Added IED and Suicide Bomber modules and other gubbins

### PR DESCRIPTION
**Pull request by CreepPork**
Added the IED module
Added Suicide Bomber module
Added all the requirement functions for them
Added localization needed for them.

And some tweaks 😄

### CODE REVIEW

**Comment by CreepPork** [comment]
@oOKexOo you should build it and see if it works, I didn't build it and try it out. Tell me if there are any issues.

**Comment by oOKexOo** [comment]
Thx for the pull request. I'll check it out and let you know.

**Comment by Snak3Doc** [comment]
Great work CreepPork your a legend!

**Comment by oOKexOo** [comment]
now in dev branch

**Pull request closed without merging**
