### PR TITLE
Add pbo Prefixes

### PR DESCRIPTION
**Pull request by 654wak654**
This adds `achilles_` to the front of all the pbo names to unify things a bit.

### CODE REVIEW

**Comment by oOKexOo** [comment]
I want to maintain a similar naming as in ArmA 3 vanilla add-ons (e.g. A3_modules_f_curator)
The naming of the subclasses of cfgPatches, pbo names and prefixes were chosen accordingly.
I see that names such as achilles_modules_f_achilles might be irritating, I could change it to AMAE_modules_f_achilles for instance and use AMAE as the main directory.

**Comment by 654wak654** [comment]
The vanilla addons are their own thing; maybe you should consider using community naming conventions instead of having a pbo that's just called `ui_f`. We don't even know for sure what the `_f_` stands for in BI's addons, so why follow it?

`achilles_modules_f` is still close to the vanilla, but indicates better that it's part of the `achilles` mod.

**Comment by oOKexOo** [comment]
Thank you for your explanation. I got your point. If someone want to merge add-ons, it is better to have a prefix. Hence, I will adopt the prefix. However, I want to keep the postfix _achilles for two reasons:
1) The community relys on the cfgPatches name achilles_modules_f_achilles. They use it to detect if achilles is present.
2) It is also an indication for me that the pbo only contains achilles related stuff.

**Comment by 654wak654** [comment]
1. Valid point, bwc is important.
2. The ares pbos still have `_ares` at the end, so you can still differentiate. Same with the pboprefixes, no need to have two achilles both at the start and end IMO, but it's ultimately your call.

**Comment by Grezvany13** [comment]
I would even go a step further and follow the naming conventions of CBA:

Paths: MAINPREFIX\PREFIX\SUBPREFIX\COMPONENT\SCRIPTNAME.sqf
e.g: x\achilles\addons\modules_ares\someFile.sqf

This way the namespace will never interfere with other mods/addons, unless the exact same names are used (which is unlikely to happen).

It also means that the pbo filenames DO NOT have any prefix/suffix, which only makes stuff more complicated (IMHO).

I suggest to keep is as simple as possible:
- /addons/modules.pbo => \x\achilles\addons\modules
- /addons/modles_ares.pbo => \x\achilles\addons\modules_ares

or even merge all Ares and Achilles code into a single PBO, which would be my preference.


As for the cfgPatches name achilles_modules_f_achilles; technically this is correct (even according to the CBA standards), although those are a lot of "words" to only indicate it contains 'modules' within 'achilles' (for 'achilles' and some strange 'f' suffix).

Since the mod is officially still in Alpha status (although heavily used), it should be fine to rename/rewrite the names and code, as long as the changes are communicated to the community (a notification beforehand, and a complete changelog on release). And by changing the version number, everyone can see the difference. Even ArmA is not fully backwards compatible.

**Comment by oOKexOo** [comment]
@Grezvany13 
You're right. This add-on is still in alpha stage for a reason.
I'm currently very busy. I expect I will resume my work in 3 to 4 weeks. This is also far than enough time for me to reconsider this topic.

**Comment by oOKexOo** [comment]
This one has become outdated, but the fact still remains that a new structure is required.
I've come to like the ACE3 naming convention which I probably will adapt in future. I will however adjust it the way that the functions are still compatible with the function viewer.

**Pull request closed without merging**
